# Generated by Django 3.1.2 on 2021-08-29 06:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(choices=[('Web Development', 'Web Development'), ('Backend Development', 'Backend Development'), ('Frontend Development', 'Frontend Development'), ('Content Writing', 'Content Writing'), ('Digital Marketing', 'Digital Marketing'), ('Android App Development', 'Android App Development')], max_length=50)),
                ('skills', models.TextField()),
                ('duration', models.PositiveIntegerField()),
                ('activities', models.TextField()),
                ('perks', models.CharField(max_length=300)),
                ('amount', models.PositiveIntegerField()),
                ('comp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.company')),
                ('user1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stud_name', models.CharField(max_length=350)),
                ('address', models.TextField()),
                ('mobile', models.PositiveIntegerField()),
                ('class_12', models.PositiveIntegerField()),
                ('class_10', models.PositiveIntegerField()),
                ('persuing', models.CharField(choices=[('B-TECH', 'B-TECH'), ('BBA', 'BBA'), ('M-TECH', 'M-TECH'), ('MCA', 'MCA')], max_length=25)),
                ('pro_img', models.ImageField(blank=True, null=True, upload_to='profile_img')),
                ('experience', models.TextField(blank=True)),
                ('cv', models.FileField(blank=True, null=True, upload_to='cv_all')),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Apply',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.candidate')),
                ('posts', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.job')),
            ],
        ),
    ]
