# Generated by Django 3.1.2 on 2021-08-29 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='desc',
            field=models.TextField(default=True),
        ),
    ]
