# Generated by Django 3.1.2 on 2021-08-30 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_company_desc'),
    ]

    operations = [
        migrations.RenameField(
            model_name='company',
            old_name='user',
            new_name='user2',
        ),
        migrations.AlterField(
            model_name='company',
            name='desc',
            field=models.TextField(default=''),
        ),
    ]
