# Generated by Django 3.1.2 on 2021-08-30 06:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20210830_1151'),
    ]

    operations = [
        migrations.RenameField(
            model_name='company',
            old_name='user2',
            new_name='user',
        ),
    ]
