# Generated by Django 3.1.2 on 2021-08-30 13:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20210830_1154'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Apply',
        ),
    ]
