# Generated by Django 3.1.2 on 2021-08-30 14:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_application'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='cd',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.candidate'),
        ),
    ]
